travis:
  secure:
    BINSTAR_TOKEN: QxKRieTnl0VnDRcvlkrZTgLz0RDAj7Rd1mZUubohc+ah1B+f+DYjwGggf8ZY4aYIqP4NW+6KWSYyEAmQlc7CsVE1vj0o9sq6Gn8O2LIySxJ7wV06eVyIfSKIiZaVwfry41Nql2nDVUMNUUI9Y449ngyvxV+zSU90sKWCM/o3NiTn5p4bkk+BIE2p8DG9RTobw1OE9TH6JsQTgciBYwhymVF98O6GlHN4c+gab0ZfIlULQQmNUDj0Wn2iTI1YH23oqw5gZBmfVKyRiDy0p3BKoPUjy388wbN02yBM8wX7O2lY0tKSxDoHwfJ1YKLfOndYjB5Kg2aNIRhdM/IzO18+YDDZH2sSooi/yOlbRCEm81VdMuq2FWXKoSYdiNC9KqJSxCGhcVwWNf0U3iRKzmK5rSqfDJJXRnGHGTmw0qQy5JC+7kKwFv0QTpCjzeVUkWIsWMrASRSAhPVx/61RgXzwcgBdHcTAj9ls0NednwbHvXNyWoHQunKs0cWvlCJ2MvQW5M7JrlS4pUMNfjNm/ku50FMsuBBkA95IDHntcQqSXlflgUEBPMsZztsYhKxhOAy3d4YH/0rKI70bSoMlp4prnMR0j2W/0bqKmCicaSnQ1xYMqrhmddQ9R4Dz+wZHS94n9mq3m9ofFWW+r5XjFSTYuSr6h2nonqqDFCHgTcFVnD0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
